name: NIGHTLY-CI

on:
   schedule:
    - cron: '31 23 * * *'

env:
 HOME: /root
 PYTHONUNBUFFERED: true
 CLIENT: local
 CLUSTER: agent-based
 PULLSECRET: /root/openshift_pull.json
 INVENTORY: .github/inventory_ci.yml
 EXTRA_ANSIBLE_PARAMS: "-e operators=kubevirt-hyperconverged,metallb-operator -e nodes=3"

jobs:
    requirements:
      runs-on: libvirt
      steps:
       - uses: actions/checkout@v2
       - run: git pull origin ${GITHUB_REF##*/}
       - name: Install ansible
         run: which ansible-playbook || yum -y install ansible
       - name: Install kcli
         run: |
           curl https://raw.githubusercontent.com/karmab/kcli/master/install.sh | bash
           kcli create sushy-service
       - name: Clean up
         continue-on-error: true
         run: |
           kcli -C $CLIENT delete plan --yes $CLUSTER || true
           [ -d $CLUSTER ] && rm -rf $CLUSTER
           kcli -C $CLIENT delete iso --yes $CLUSTER.iso || true

    deploy-kcli-plan:
      needs: requirements
      runs-on: libvirt
      steps:
      - name: Deploy kcli plan
        run: |
          kcli -C $CLIENT create plan $CLUSTER

    deploy-agent-based-cluster:
      needs: deploy-kcli-plan
      runs-on: libvirt
      steps:
      - name: Deploy agent based cluster
        run: |
          grep -q "^192.168.128.253 api.$CLUSTER.karmalabs.corp" /etc/hosts || echo 192.168.128.253 api.$CLUSTER.karmalabs.corp >> /etc/hosts
          ansible-playbook -i $INVENTORY run.yml $EXTRA_ANSIBLE_PARAMS

    clean-up:
      needs: deploy-agent-based-cluster
      runs-on: libvirt
      steps:
      - name: Clean everything after success
        run: |
          kcli -C $CLIENT delete plan --yes $CLUSTER
          [ -d $CLUSTER ] && rm -rf $CLUSTER
          kcli -C $CLIENT delete iso --yes $CLUSTER.iso || true
